language: python
python:
# - "3.6"      # current default Python on Travis CI
  - "3.7"

addons:
  apt:
    packages:
      - docker-ce
  artifacts:
    working_dir: /tmp
    target_paths:
      - _data

before_install:
  - docker pull guneysu/prayer-times-api:latest
  - pip3 install awscli --upgrade

install:
  - pip install -r requirements.txt

script: 
  - make up
  - docker ps
  - sudo chmod +rwx . -R
  - python3 updater.py -c istanbul -p daily -h http://127.0.0.1:8000 -b ${ARTIFACTS_FOLDER}
  # - make update_daily
  # - make update_weekly
  # - make update_monthly


