language: python
python:
# - "3.6"      # current default Python on Travis CI
  - "3.7"

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker pull guneysu/prayer-times-api:latest
  

install:
  - pip install -r requirements.txt

script: 
  - make up
  - python3 -c istanbul -p daily -h http://127.0.0.1:8000 -b /tmp
  # - make update_daily
  # - make update_weekly
  # - make update_monthly


