version: "3.7"

services:
  api:
    # build:
    #   context: .
    image: guneysu/prayer-times-api:latest
    ports:
      - "8001:80"
    restart: on-failure


  agent:
    build:
       context: .
       dockerfile: tasks/Dockerfile
    volumes:
      - ./_data:/data
    links:
      - api:api
