openapi: 3.0.0
info:
  version: "v1.1"
  title: 'Prayer Times API'
  description: 'Prayer Times API'
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/guneysus/prayer-times/v1
  - description: AWS S3 Bare
    url: http://api.namazvakti.guneysu.xyz.s3-website-us-east-1.amazonaws.com
  - description: Production Domain
    url: http://api.namazvakti.guneysu.xyz
    
paths:
  /{city}/daily:
    get:
      description: Returns daily prayer times
      parameters:
        - $ref: '#/components/parameters/City'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/PrayerTime'

  /{city}/weekly:
    get:
      description: Returns weekly prayer times
      parameters:
        - $ref: '#/components/parameters/City'    
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/WeeklyPrayerTimes'       
                
  /{city}/monthly:
    get:
      description: Returns monthly prayer times
      parameters:
        - $ref: '#/components/parameters/City'    
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/MonthlyPrayerTimes'                
components:
  schemas:
    PrayerTime:
      type: object
      properties:
        fajr:
          type: string
          example: 06:49
        sunrise:
          type: string
          example: 08:21
        dhuhr:
          type: string
          example: 13:10
        asr:
          type: string
          example: 15:28
        maghrib:
          type: string
          example: 17:49
        isha:
          type: string
          example: 19:15
        hijri:
          type: string
          example: 1 C.EVVEL 1441
        gregorian:
          type: string
          example: 27 Aralık 2019 Cuma                   
    
    WeeklyPrayerTimes:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/PrayerTime'
            
    MonthlyPrayerTimes:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/PrayerTime'
  parameters:
    City:
      name: city
      in: path
      required: true
      schema:
        type: string
        pattern: (istanbul|ankara|bursa|erzurum|eskisehir|gaziantep|izmir|kayseri|konya|sakarya|tekirdag)